### PR TITLE
cleanup and use jbakeconfig to initialize jbake

### PR DESCRIPTION
**Pull request by ancho**
The upcoming release of jbake includes an update to apache commons2.
The plugin should not use the deprecated constructors to initialize the Oven and use a DefaultJBakeConfiguration instead.

I removed the Proxy Implementations to use the WorkerExecutor mechanism instead and therefor deprecated the use of gradle <= 5.6. The Readme already defines gradle 6+ as a requirement.

### CODE REVIEW

**Comment by jonbullock** [comment]
Need to either close this or merge it in prior to the plugin moving to the jbake repo.

**Comment by aalmiray** [comment]
@ancho I've updated license headers as that made the merge fail on CI. However I've got failures when running tests locally. If the latest action were to fail, could you have a look? https://github.com/jbake-org/jbake-gradle-plugin/actions/runs/1646899607

**Comment by ancho** [comment]
This seems to be related with the license headers. If I remove those from the template and content files in src/test/resources/example-project the test passes locally.

**Comment by aalmiray** [comment]
Thank you, that does the trick! 😄

**Comment by jonbullock** [comment]
Thanks @aalmiray @ancho

**Pull request merged**
