### PR TITLE
Upgraded to jbake version 2.5

### PR DESCRIPTION
**Pull request by danielgrycman**

### CODE REVIEW

**Comment by aalmiray** [comment]
@danielgrycman one of the tests is broken due to the upgrade. Please see https://travis-ci.org/jbake-org/jbake-gradle-plugin/builds/168197089 for details. It's a good idea to run `gradlew build` before sending a pull request 😏

**Comment by danielgrycman** [comment]
@aalmiray Everything should be fine now :)

**Comment by danielgrycman** [comment]
@aalmiray Everything should be fine now :).

**Comment by aalmiray** [comment]
thank you! 😄

**Pull request merged**
