### PR TITLE
Upgrade to JBake 2.6.0 

### PR DESCRIPTION
**Pull request by danielkocot**

### CODE REVIEW

**Comment by ancho** [comment]
Thank you. Just one addition you couldn't be aware of. Can you align the Versions in [JBakeExtension](https://github.com/jbake-org/jbake-gradle-plugin/blob/master/src/main/groovy/org/jbake/gradle/JBakeExtension.groovy) with the versions from [jbake 2.6.0](https://github.com/jbake-org/jbake/blob/v2.6.0/build.gradle#L11)?

**Comment by danielkocot** [comment]
@ancho Is it possible to fix the oraclejdk7-Build?

**Comment by danielkocot** [comment]
@aalmiray Is it possible to release a new version before JavaLand? :)

**Comment by aalmiray** [comment]
Yes, of course :-)

**Pull request merged**
