### PR TITLE
Upgrade to JBake 2.4.0

### PR DESCRIPTION
**Pull request by antonmry**
I've updated the plugin to use JBake 2.4.0, I hope this will be useful for others. Let me know if I miss something, I will be happy to correct it. I've added also my blog as example.

I found some problems with the test regarding the previous versions. I am not sure if it's a good idea maintain test for previous versions instead of evolve the plugin following the jbake version. Let me know if it makes sense for you and I will refactor the test.

### CODE REVIEW

**Comment by danielgrycman** [comment]
:+1: @antonmry Could you change the asciidoctorj to 1.5.4? :-)

**Comment by ancho** [comment]
:+1:

The Test for previous Versions of jbake are written to make sure that the right library of asciidoctorj is used as dependency at runtime by the gradle plugin. It changed between 2.3.0 and 2.3.1. Hence the test to make sure the plugin consider this.

It makes totally sense to keep the versions up to date as jbake evolves, even if you are able to override them with your build script, to make sure the plugin uses the preferred versions of jbake.

**Comment by ancho** [comment]
2.4.0 uses asciidoctorj 1.5.2 as you can see here: https://github.com/jbake-org/jbake/blob/master/pom.xml#L68

The Versions in JbakeExtension should reflect the dependent Versions of the current stable jbake release.

**Comment by antonmry** [comment]
@danielgrycman, I prefer to align with the jbake version as @ancho has explained. It seems jbake 2.5.0 will use asciidoctorj 1.5.2 https://github.com/jbake-org/jbake/blob/master/pom.xml

Maybe open an issue in https://github.com/jbake-org/jbake/ if it's not already opened is the best way to proceed.

**Comment by antonmry** [comment]
@ancho, I'm not saying to eliminate the version check for the current version but for the previous versions. Right now, you can download the latest source code and select what jbake version you want to use... so the plugin maintainer should be maintain the test for all the versions. I don't see any advantage on it, if you want to use a previous jbake versions, just download the previous version of the gradle plugin.

My proposal for the test would be:

1. Version tests only for the current jbake version. Eliminate the test for previous versions and the "select version" functionality.
2. Add tests for markdown, asciidoctor generation adding a init task and the corresponding tests.

**Comment by danielgrycman** [comment]
@antonmry I open a PR with AsciidoctorJ 1.5.4 jbake-org/jbake#255.

**Comment by jonbullock** [comment]
Thanks @antonmry - if anyone is interested in helping maintain this plugin please see #17

**Comment by ancho** [comment]
@antonmry The tests where introduced with #7 to make the version of jbake configurable to be independent on a gradle plugin release.

You can test a snapshot version or even use the current release of jbake now.

I think it doesn't hurt to test the switch to an older version.
So as long as the jbake version is configurable by the plugin this particular behaviour should be tested.

The convention should be to expect the usage of the latest jbake version with the latest plugin release but be free to switch the version of template engines and jbake by configuration.

**Comment by aalmiray** [comment]
We've updated the version with a different commit. Thank you very much for your support :smile:

**Pull request closed without merging**
