### PR TITLE
jbakeClean task and and jbake renamed to jbakeBuild

### PR DESCRIPTION
**Pull request by antonmry**
I've implemented a very basic clean task as requested in #11. I named jbakeClean and renamed jbake to jbakeBuild, if another naming is preferred, just let me know and I will update the PR. My idea is to add jbakeInit and jbakeServer tasks in the same way with some integration tests.

### CODE REVIEW

**Comment by ancho** [comment]
The plugin applies the gradle base plugin. See https://github.com/jbake-org/jbake-gradle-plugin/blob/master/src/main/groovy/me/champeau/gradle/JBakePlugin.groovy#L31

A ```gradle clean``` should work out of the box.

I opened a renaming pull request a while ago. See #12.
For jbakeInit an jbakeServer and a few other tasks @mperry opened a pull request #5.

Maybe @jonbullock or @melix can give us a few thoughts about their vision and the future plan of this plugin.

**Comment by antonmry** [comment]
Yes, 'gradle clean' works well :+1:

It would be great to have some guidance from them, it seems there are lot of people trying to contribute to it and it's just a matter of coordination.

**Comment by jonbullock** [comment]
I've just not had enough time to look into this plugin and devote the time it requires along side JBake, so I've started the ball rolling on letting somebody else take responsibility for this plugin and it's maintenance - see #17 - of course I'm happy to advise where needed especially in relation to JBake core.

**Comment by aalmiray** [comment]
Closing this PR as the behavior is already provided

**Pull request closed without merging**
